### ISSUE TITLE
Roadmap to AMCC v2

### ISSUE THREAD

**Issue by Defective4** [Defective4/Another-Minecraft-Chat-Client#24]
This issue contains changes that are planned in the (not so distant) future.
The list is **not** ordered.
The list may be updated with new entries as needed.

### Code
- [x] Refactor (listeners, packet structue, etc.)
- [x] Public API/Plugins #14
- [x] Migrate to Maven (was using Gradle)
- [ ] Item IDs, names and textures rework.
- [ ] Repair inventory handling on newer versions
- [x] Change preferences file format

### UI/UX
- [x] Completely separate UI from protocol (the protocol implementation was dependent on UI)
- [ ] Create a CLI version
- [ ] Create an Android app
- [x] Update language files
- [x] Update Chinese translation #26
- [x] Support loading servers list from Minecraft instalation 

### Maven
- [x] Upload public API to maven
- [x] Upload separated protocol implementation to maven

### Features
- [ ] Improve existing features
- [ ] Add Forge support for newer versions
- [x] Add Microsoft authentication
- [x] Remove Mojang authentication

### GitHub
- [x] New Readme.md
- [x] Wiki

### Versions
- [ ] 1.19.3
- [ ] 1.19.4
